[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && pip install -r requirements-prod.txt"

[deploy]
startCommand = "python download_models.py && python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { DEBUG = "False", RAILWAY_DEPLOYMENT = "True" }
production.packageOverrides = ["python311", "libgl1-mesa-glx", "libglib2.0-0"]
