[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && pip install -r requirements.txt"

[deploy]
startCommand = "python startup.py"
healthcheckPath = "/api/core/"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { DEBUG = "False", RAILWAY_DEPLOYMENT = "True" }
