[build]
builder = "nixpacks"
buildCommand = "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "python startup_simple.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckGracePeriod = "300s"

[environments]
production.packageOverrides = ["python311", "libgl1-mesa-glx", "libglib2.0-0", "postgresql-client", "libglib2.0-0", "libsm6", "libxext6", "libxrender-dev", "libgomp1"]

[[healthchecks]]
interval = "30s"
timeout = "10s"
method = "GET"
path = "/admin/login/"
port = "8000"
initialDelay = "30s"