[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn backend.wsgi:application --bind 0.0.0.0:8080 --workers 3 --access-logfile - --error-logfile -"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { 
    DEBUG = "False", 
    RAILWAY_DEPLOYMENT = "True",
    PYTHONUNBUFFERED = "1",
    DJANGO_SETTINGS_MODULE = "backend.settings",
    AWS_S3_REGION_NAME = "us-east-1",
    DISABLE_SSL_REDIRECT = "True"
}
