[build]
builder = "nixpacks"

[deploy]
startCommand = "python startup_simple.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments]
production.packageOverrides = ["python311", "libgl1-mesa-glx", "libglib2.0-0", "postgresql-client"]