[build]
builder = "nixpacks"
buildCommand = "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"

[environments]
production.packageOverrides = ["python311", "libgl1-mesa-glx", "libglib2.0-0"]