# Generated by Django 5.2.5 on 2025-09-05 08:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('unknown', 'Unknown')], default='unknown')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('willing_to_donate', models.BooleanField(default=False)),
                ('has_chronic_condition', models.BooleanField(default=False, null=True)),
                ('condition_controlled', models.BooleanField(default=False, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('recent_tattoo_or_piercing', models.BooleanField(default=False, null=True)),
                ('ate_fatty_food', models.BooleanField(default=False, null=True)),
                ('ate_before_donation', models.BooleanField(default=True, null=True)),
                ('had_alcohol_last_24h', models.BooleanField(default=False, null=True)),
                ('sleep_hours', models.IntegerField(blank=True, default=None, null=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('participant_data', models.JSONField()),
                ('diabetes_result', models.JSONField(blank=True, null=True)),
                ('blood_group_result', models.JSONField(blank=True, null=True)),
                ('fingerprints', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='uploads/fingerprints/')),
                ('pattern', models.CharField(blank=True, max_length=20, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes_risk', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+')], max_length=3)),
                ('blood_group_confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.participant')),
            ],
        ),
    ]
