# Generated by Django 5.2.5 on 2025-09-05 09:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='image',
            field=models.ImageField(upload_to=core.models.fingerprint_upload_path),
        ),
    ]
